language: java
sudo: true
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE pontointeligente;'
services:
  - mysql 
